#!/bin/bash
#
# Clone a VM. Assumes domains are in the format "gza#" and network
# configs have already been set up.
#
# To ensure cloned VMs have the proper IP address---instead of just using the
# IP assigned to gza0---start gza0, issue ipconfig /release, and immediately shut
# down the VM. This will force the new VMs to renew the IP and get assigned the
# proper one before creating the snapshot. Afterwards run ./makesnapshot gza0 and
# you should be good2go.
#

machex() {
  echo "obase=16; $1" | bc | tr '[A-F]' '[a-f]'
}

# current debian squeeze version has a bug so let's specify a newer version
VIRTCLONE=/home/yacin/tarballs/virtinst-0.600.3/virt-clone
POOLDIR=/images # the pool directory for virsh

if [[ ($# -ne 1 && $# -ne 2) || "$(id -u)" != "0" ]]; then
    echo "usage: sudo ./clonevm gza# [imgstoredir] (always clones from gza0)"
    echo "second argument is the directory to store the images if you'll be symlinking them to a tmpfs store"
    exit 2
fi

fromvm=gza0
tovm=$1
fromvmnum=$(echo $fromvm | tr -d 'gza')
tovmnum=$(machex "$(echo $tovm | tr -d 'gza')")

$VIRTCLONE -o $fromvm -n $tovm -m aa:bb:cc:dd:ee:$tovmnum -f $POOLDIR/$tovm.img

# use this if the images will be symlinked to the pooldir and the pooldir
# will be mounted as a tmpfs directory for speed
if [[ $# -eq 2 ]]; then
  IMGSTOREDIR=$2
  mv /$POOLDIR/$tovm.img /$IMGSTOREDIR/$tovm.img
  ln -s /$IMGSTOREDIR/$tovm.img /$POOLDIR/$tovm.img
fi

sleep 10
./makesnapshot $tovm
